# Generated by Django 2.1.1 on 2018-10-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Login', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('URL', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('User_name', models.CharField(max_length=30, unique=True)),
                ('Master_password_hash', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_record',
            fields=[
                ('pair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='psswdmng.Pair')),
                ('Password', models.CharField(max_length=50)),
                ('Change_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psswdmng.User')),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psswdmng.Login'),
        ),
        migrations.AddField(
            model_name='pair',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psswdmng.Resource'),
        ),
    ]
