# Generated by Django 2.1.1 on 2018-10-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psswdmng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Login', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('URL', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='Main_table',
            fields=[
                ('pair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='psswdmng.Pairs')),
                ('Password', models.CharField(max_length=50)),
                ('Change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pairs',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psswdmng.Logins'),
        ),
    ]
