# Generated by Django 2.1.1 on 2018-11-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psswdmng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Authentication_sequence',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Open_key',
            field=models.BinaryField(default=b'\x00'),
            preserve_default=False,
        ),
    ]
