# Generated by Django 2.1.1 on 2018-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psswdmng', '0002_auto_20181118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Authentication_sequence',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
