# Generated by Django 2.1.1 on 2018-10-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psswdmng', '0002_auto_20181003_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logins',
            new_name='Login',
        ),
        migrations.RenameModel(
            old_name='Main_table',
            new_name='Main_record',
        ),
        migrations.RenameModel(
            old_name='Pairs',
            new_name='Pair',
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
