# Generated by Django 2.1.1 on 2018-11-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psswdmng', '0003_auto_20181118_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Authentication_sequence',
            field=models.BinaryField(null=True),
        ),
    ]
