# Generated by Django 2.1.1 on 2018-12-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psswdmng', '0004_auto_20181118_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Session_started',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='login_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main_record',
            name='pair_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='psswdmng.Pair'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='pair_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Open_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
